import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Hero";
import Layout from "@/components/Layout";
import Menu from "@/components/Menu";
import Services from "@/components/Services";
import Sourdough from "@/components/Sourdough";
import DoughVideo from "@/components/DoughVideo";
import Introduction from "@/components/Introduction";
import CurrentLocation from "@/components/CurrentLocation";

export default function Home({ locationData }) {
  console.log(locationData);
  return (
    <>
      <Head>
        <title>Masa Madre Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Layout>
          <Hero />
          {locationData.length === 0 ? null : (
            <CurrentLocation locationData={locationData} />
          )}
          <Menu />
          <DoughVideo />
          <Introduction />
          <Services />
          <Sourdough />
        </Layout>
      </>
    </>
  );
}

const client = createClient({
  projectId: "f1rf47lg",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

import { createClient } from "next-sanity";

export async function getStaticProps() {
  const locationData = await client.fetch(
    `*[_type=="location"]{address, "imageUrl": locationPhoto.asset->url, geolocation, content, openTime, closeTime}`
  );

  return {
    props: {
      locationData,
    },
  };
}
