import Head from "next/head";
import Image from "next/image";
import Hero from "@/components/Hero";
import Layout from "@/components/Layout";
import Menu from "@/components/Menu";
import Services from "@/components/Services";
import Sourdough from "@/components/Sourdough";
import DoughVideo from "@/components/DoughVideo";
import Introduction from "@/components/Introduction";
import CurrentLocation from "@/components/CurrentLocation";
import { createClient } from "next-sanity";
import CurrentlyClosed from "@/components/CurrentlyClosed";

export default function Home({ locationData }) {
  return (
    <>
      <Head>
        <title>Masa Madre Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Layout>
          <Hero />
          {locationData.length === 0 ? (
            <CurrentlyClosed />
          ) : (
            <CurrentLocation locationData={locationData} />
          )}
          <Menu />
          <DoughVideo />
          <Introduction />
          <Services />
          <Sourdough />
        </Layout>
      </>
    </>
  );
}

const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET,
  apiVersion: "2022-03-25",
  useCdn: true,
});

export async function getStaticProps() {
  const locationData = await client.fetch(
    `*[_type=="location"]{address, "imageUrl": locationPhoto.asset->url, googleMapsUrl, content, openTime, closeTime}`
  );

  return {
    revalidate: 60,
    props: {
      locationData,
    },
  };
}
